services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ip_monitor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "9292:9292"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db/ip_monitor
      RACK_ENV: development
      DB_MAX_CONNECTIONS: 10
    depends_on:
      db:
        condition: service_healthy

  test:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@db/ip_monitor_test
      RACK_ENV: test
      DB_MAX_CONNECTIONS: 10
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["./docker-test-entrypoint.sh"]
    command: ["bundle", "exec", "rspec"]

  ping-worker:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@db/ip_monitor
      RACK_ENV: development
      DB_MAX_CONNECTIONS: 10
      PING_BATCH_SIZE: 10
      PING_CHECK_INTERVAL: 60
      PING_POLL_INTERVAL: 5
    depends_on:
      db:
        condition: service_healthy
    command: ["bundle", "exec", "rake", "ping_worker"]
    deploy:
      replicas: 1

volumes:
  pgdata:
